using Substrate.Generation.Core.Helpers;
using Substrate.Generation.Core.Nodes;
using System.Text;

namespace Substrate.Generation.Core.Documents
{
    internal sealed class TypeDocument : DocumentBase
    {
        private readonly TypeKey _key;
        private readonly Dictionary<Type, INodeBuilder> _builders = new();

        public TypeDocument(TypeKey key, IReadOnlyList<SubstrateNode> nodes)
            : base(DocumentHelpers.GetHintName(key))
        {
            _key = key;
            Register<NotifyNodeBuilder>();
            Register<DependencyPropertyNodeBuilder>();
            Register<PartialHooksBuilder>();

            DispatchNodes(nodes);
        }
        private void Register<T>() where T : INodeBuilder
        {
            var instance = (T)Activator.CreateInstance(typeof(T), this)!;
            _builders.Add(typeof(T), instance);
        }
        public T? GetBuilder<T>() where T : class, INodeBuilder
        {
            _builders.TryGetValue(typeof(T), out var builder);
            return builder as T;
        }

        private void DispatchNodes(IEnumerable<SubstrateNode> nodes)
        {
            foreach (var node in nodes)
            {
                foreach (var builder in _builders.Values)
                {
                    if (builder.Accepts(node))
                        builder.Add(node);
                }
            }
        }
        public override string Build()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Substrate.Notify");
            sb.AppendLine();
            sb.Nullable();
            sb.BlankLine();

            if (!string.IsNullOrEmpty(_key.Namespace))
            {
                sb.AppendLine($"namespace {_key.Namespace};");
                sb.BlankLine();
            }

            // partial class declaration
            sb.AppendIndented(0, $"public partial class {_key.TypeName}");
            sb.OpenBrace(0);

            foreach (var builder in _builders.Values)
            {
                if (builder.HasOutput)
                {
                    builder.Build(sb);
                }
            }

            sb.CloseBrace(0);

            return sb.ToString();
        }
        
    }
}